Repository DNNCommunity/DNN.Vendors, pull requests merged in 2019-04, with the labels that each got.

#20 Fixed issue with symbols installation
  src/Dnn.Modules.Vendors/dnn_Vendors.dnn
Labels: bug

#21 Fixed issue with resx files deployment
  src/Dnn.Modules.Vendors/BuildScripts/Module.Targets
Labels: DevOps

#23 Added png to packaged files
  src/Dnn.Modules.Vendors/build.cake
Labels: bug

#15 RFC: Feature request: responsive design #14
  src/Dnn.Modules.Vendors/Affiliates.ascx.cs
  src/Dnn.Modules.Vendors/App_LocalResources/BannerOptions.ascx.resx
  src/Dnn.Modules.Vendors/BannerOptions.ascx.cs
  src/Dnn.Modules.Vendors/BannerOptions.ascx.designer.cs
  src/Dnn.Modules.Vendors/Components/BannerController.cs
  src/Dnn.Modules.Vendors/DisplayBanners.ascx.cs
  src/Dnn.Modules.Vendors/DisplayBanners.ascx.designer.cs
  src/Dnn.Modules.Vendors/Dnn.Modules.Vendors.csproj
  src/Dnn.Modules.Vendors/Install/DNNCE_Vendors_08.00.00_Install.zip
  src/Dnn.Modules.Vendors/banneroptions.ascx
  src/Dnn.Modules.Vendors/displaybanners.ascx
  src/Dnn.Modules.Vendors/dnn_Vendors.dnn
  src/Dnn.Modules.Vendors/module.css
Labels: enhancement
